environment: dev
domain: retail_demo
system: retail_demo
entity: orders

bronze:
  enabled: true
  source_type: file
  path_pattern: ./sampledata/source_samples/pattern1_full_events/system=retail_demo/table=orders/pattern=pattern1_full_events/dt=2025-11-13/full-part-0001.csv
  partition_column: run_date
  options:
    format: csv
    load_pattern: full
    partitioning_strategy: date
  local_output_dir: ./sampledata/bronze_samples/pattern1_full_events

silver:
  enabled: false
